server:
  port: 8084

spring:
  application:
    name: board-service
  
  datasource:
    url: jdbc:postgresql://neondb_owner:npg_S37INUGMiWOl@ep-shy-lab-a6zvz628.us-west-2.aws.neon.tech/neondb?sslmode=require&ssl=true&sslcert=&sslkey=&sslrootcert=
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

google:
  translate:
    api:
      key: ${GOOGLE_TRANSLATE_API_KEY:}
      url: https://translation.googleapis.com/language/translate/v2

logging:
  level:
    com.samsung.recipe.board: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always