version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:latest
    container_name: recipe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: recipe-user-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Recipe Service
  recipe-service:
    build:
      context: ./backend/recipe-service
      dockerfile: Dockerfile
    container_name: recipe-recipe-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-formidable-byte-461400-t1}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET:-test-recipe-assets}
      - GCP_STORAGE_FOLDER=${GCP_STORAGE_FOLDER:-images}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "8082:8082"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: recipe-frontend
    ports:
      - "5000:80"
    depends_on:
      - user-service
      - recipe-service
    networks:
      - recipe-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  recipe-network:
    driver: bridge