version: '3'

services:
  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ${GCP_REGISTRY_URL}/user-service:${IMAGE_TAG:-latest}

  # Recipe Service
  recipe-service:
    build:
      context: ./backend/recipe-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ${GCP_REGISTRY_URL}/recipe-service:${IMAGE_TAG:-latest}

  # Ingredient Service
  ingredient-service:
    build:
      context: ./backend/ingredient-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ${GCP_REGISTRY_URL}/ingredient-service:${IMAGE_TAG:-latest}

  # Board Service
  board-service:
    build:
      context: ./backend/board-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ${GCP_REGISTRY_URL}/board-service:${IMAGE_TAG:-latest}

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=${NODE_ENV}
    platform: linux/amd64
    image: ${GCP_REGISTRY_URL}/frontend:${IMAGE_TAG:-latest} 