version: '3'

services:
  # Database
  postgres:
    image: postgres:latest
    container_name: recipe-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:latest
    container_name: recipe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: asia-northeast3-docker.pkg.dev/formidable-byte-461400-t1/dev-asia-northeast3-repo/user-service:latest
    container_name: recipe-user-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Recipe Service
  recipe-service:
    build:
      context: ./backend/recipe-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: asia-northeast3-docker.pkg.dev/formidable-byte-461400-t1/dev-asia-northeast3-repo/recipe-service:latest
    container_name: recipe-recipe-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8082:8082"
    volumes:
      - recipe_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Ingredient Service
  ingredient-service:
    build:
      context: ./backend/ingredient-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: asia-northeast3-docker.pkg.dev/formidable-byte-461400-t1/dev-asia-northeast3-repo/ingredient-service:latest
    container_name: recipe-ingredient-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped
    

  # Board Service
  board-service:
    build:
      context: ./backend/board-service
      dockerfile: Dockerfile
    platform: linux/amd64
    image: asia-northeast3-docker.pkg.dev/formidable-byte-461400-t1/dev-asia-northeast3-repo/board-service:latest
    container_name: recipe-board-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=${NODE_ENV}
    platform: linux/amd64
    image: asia-northeast3-docker.pkg.dev/formidable-byte-461400-t1/dev-asia-northeast3-repo/frontend:latest
    container_name: recipe-frontend
    ports:
      - "5000:80"
    depends_on:
      - user-service
      - board-service
      - recipe-service
      - ingredient-service
    networks:
      - recipe-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  recipe_uploads:

networks:
  recipe-network:
    driver: bridge