version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    container_name: recipe-postgres
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: recipe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: recipe-user-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/recipe_db
      DB_USERNAME: recipe_user
      DB_PASSWORD: recipe_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: samsung-recipe-platform-secret-key-2024-very-secure
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Recipe Service
  recipe-service:
    build:
      context: ./backend/recipe-service
      dockerfile: Dockerfile
    container_name: recipe-recipe-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/recipe_db
      DB_USERNAME: recipe_user
      DB_PASSWORD: recipe_password
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Ingredient Service
  ingredient-service:
    build:
      context: ./backend/ingredient-service
      dockerfile: Dockerfile
    container_name: recipe-ingredient-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/recipe_db
      DB_USERNAME: recipe_user
      DB_PASSWORD: recipe_password
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Board Service
  board-service:
    build:
      context: ./backend/board-service
      dockerfile: Dockerfile
    container_name: recipe-board-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/recipe_db
      DB_USERNAME: recipe_user
      DB_PASSWORD: recipe_password
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: recipe-frontend
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - recipe-service
      - ingredient-service
      - board-service
    networks:
      - recipe-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  recipe-network:
    driver: bridge