server:
  port: 8083

spring:
  application:
    name: ingredient-service
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/recipe_db}
    username: ${DB_USERNAME:recipe_user}
    password: ${DB_PASSWORD:recipe_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    modules:
      - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
  
  # Redis 설정 비활성화 (JPA와 충돌 방지)
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   timeout: 2000ms
  #   jedis:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0

jwt:
  secret: ${JWT_SECRET:samsung-recipe-platform-secret-key-2024-very-secure}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.samsung.recipe.user: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always