apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  namespace: samsung-recipe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
      - name: recipe-service
        image: samsung-recipe/recipe-service:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        # 기존 PostgreSQL 연결 (주석 처리)
        # - name: DATABASE_URL
        #   value: "jdbc:postgresql://postgres-service:5432/samsung_recipe"
        # - name: PGUSER
        #   value: "postgres"
        # - name: PGPASSWORD
        #   value: "password"
        
        # GCP Cloud SQL 연결 (새로 추가)
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gcp-cloud-sql-secret
              key: gcp-sql-connection-name
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gcp-cloud-sql-secret
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gcp-cloud-sql-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gcp-cloud-sql-secret
              key: db-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: UNSPLASH_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: external-api-secrets
              key: unsplash-access-key
        - name: STORAGE_TYPE
          value: "gcp"  # "local" 또는 "gcp"
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-storage-secrets
              key: gcp-project-id
        - name: GCP_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: gcp-storage-secrets
              key: gcp-storage-bucket
        - name: GCP_STORAGE_FOLDER
          value: "test-recipe-assets"  # 환경별로 다른 폴더 사용 가능
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/gcp/credentials/service-account-key.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: "/etc/gcp/credentials"
          readOnly: true
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-storage-secrets
          items:
          - key: gcp-service-account-key
            path: service-account-key.json
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: samsung-recipe
spec:
  selector:
    app: recipe-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP