apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: samsung-recipe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: samsung-recipe/user-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres-service:5432/samsung_recipe"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "password"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          value: "samsung-recipe-platform-secret-key-2024-very-secure"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: samsung-recipe
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP