server:
  port: 8081

spring:
  application:
    name: user-service
    
  datasource:
    # 로컬 PostgreSQL 연결 (주석 처리)
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:recipe_db}
    username: ${DB_USER:recipe_user}
    password: ${DB_PASSWORD:recipe_password}
    driver-class-name: org.postgresql.Driver
    
    # GCP Cloud SQL 직접 연결 (쿠버네티스에서 실행 시)
    # url: jdbc:postgresql:///${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${DB_HOST}
    # username: ${DB_USER}
    # password: ${DB_PASSWORD}
    # driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    modules:
      - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.samsung.recipe.user: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
