server:
  port: 8082

spring:
  application:
    name: recipe-service
  
  datasource:
    url: jdbc:postgresql://neondb_owner:npg_S37INUGMiWOl@ep-shy-lab-a6zvz628.us-west-2.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

unsplash:
  access:
    key: ${UNSPLASH_ACCESS_KEY:}
  api:
    url: https://api.unsplash.com

logging:
  level:
    com.samsung.recipe.recipe: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always